### ISSUE TITLE
Build Fail: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by StephenGilboy** [jakejarvis/hugo-build-action#2]
The action is failing when trying to build because `postcss` is not found.

![Screen Shot 2020-09-21 at 7 36 32 PM](https://user-images.githubusercontent.com/827735/93834552-ea2b4700-fc41-11ea-80bf-80f6c523d062.png)

**Comment by StephenGilboy** [comment]
To fix the issue I added `postcss` to line 34 in the Dockerfile

 `npm install --global postcss postcss-cli autoprefixer @babel/core @babel/cli && \`

**Comment by pacoispaco** [comment]
@StephenGilboy fix works for me too.

**Comment by jakejarvis** [comment]
Thanks everyone and apologies for the long delay in getting to this!
